# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
import numpy as np
a =np.arange(10)
np.resize(a, 10).reshape(2,5)
# print 2D array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [12]:
a=np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
b=np.array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [17]:
import numpy as np
x = np.arange(10).reshape(2,5)
y=np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]).reshape(2,5)
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [19]:
array = np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
flattened_array = array.flatten()
flattened_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [16]:
import numpy
v=numpy.arange(15).reshape(5,3)
numpy.ndarray.flatten(v) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [4]:
import numpy
v=numpy.arange(15).reshape(5,3)
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [5]:
b=v=numpy.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
b*b

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [5]:
import numpy as np
arr=np.arange(30). reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
x=np.mean(arr)
x

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [3]:
import numpy as np
arr=np.arange(30). reshape(5,6)
w=np.std(arr)
w

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [12]:
v=np.median(arr)
v

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [5]:
import numpy as np
arr=np.arange(30). reshape(5,6)
b=np.transpose(arr)
b

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [6]:
n_array=np.arange(16).reshape(4,4)
print("Numpy Matrix is:") 
print(n_array) 
  
# calculating the Trace of a matrix 
trace = np.trace(n_array) 
  
  
print("\nTrace of given 3X3 matrix:") 
print(trace) 

Numpy Matrix is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Trace of given 3X3 matrix:
30


## Question:13

### Find the determinant of the previous array in Q12?

In [10]:
import numpy 
n_array=numpy.arange(16).reshape(4,4)
print("Numpy Matrix is:") 
print(n_array)
print("determinant is:") 
numpy.linalg.det(n_array)

Numpy Matrix is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
determinant is:


0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [12]:
a=np.arange(100)
np.percentile(a,5)

4.95

In [13]:
a=np.arange(100)
np.percentile(a,95)

94.05

## Question:15

### How to find if a given array has any null values?

In [14]:
myarray=np.arange(5)
numpy.isnan(myarray).any()

False